language: haxe

# TravisCI by default run on linux.
# Let's enable both linux and mac builds because why not?
os:
  - linux
  - osx

# Test with Haxe 3.2.1 and Haxe development.
haxe:
  - "3.2.1"
  - development

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

addons:
  # This is the preferred way to install apt packages.
  # However, it only allow some but not all packages.
  # Alternatively, we can use `sudo apt-get install ...` in the `install:` section.
  # http://docs.travis-ci.com/user/apt/#Adding-APT-Packages
  apt:
    packages:
      # Flash
      - libcurl3:i386
      - libglib2.0-0:i386
      - libx11-6:i386
      - libxext6:i386
      - libxt6:i386
      - libxcursor1:i386
      - libnss3:i386
      - libgtk2.0-0:i386

install:
  - git clone --recursive https://github.com/DoclerLabs/hexUnit.git ~/hexunit
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      export AUDIODEV=null;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew install mono;
      brew install phantomjs;
      brew install python3;
    fi
  # Download and setup a standalone flash player debugger
  - haxe flash/install.hxml

script:
  - haxe build-js.hxml           && node bin/MainCoreTest.js
  - haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/MainCoreTest.swf
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com
