sudo: required
dist: trusty

language: haxe

os:
  - linux

# haxe versions : http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.7"
  - development

env:
  - HAXE_TARGET=cpp
  #- HAXE_TARGET=cs
  - HAXE_TARGET=flash
  #- HAXE_TARGET=lua
  - HAXE_TARGET=neko
  - HAXE_TARGET=node
  - HAXE_TARGET=php
  - HAXE_TARGET=php7
  #- HAXE_TARGET=python
  - HAXE_TARGET=js
  #- HAXE_TARGET=java
  - HAXE_TARGET=hl

matrix:
  fast_finish: true
  allow_failures:
    - haxe: development
    - env: HAXE_TARGET=flash # cannot trust that guy
    - env: HAXE_TARGET=cpp # Not supported yet
    - env: HAXE_TARGET=cs # Not supported yet
    - env: HAXE_TARGET=lua # Not supported yet
    - env: HAXE_TARGET=python # Not supported yet
    - env: HAXE_TARGET=java # Not supported yet
    - env: HAXE_TARGET=hl # Not supported yet
  exclude:
    - haxe: "3.4.7"
      env: HAXE_TARGET=hl
    
before_install:
  - echo $TRAVIS_BRANCH
  - export DEPENDENCIES_BRANCH=$TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - if [[ "$TRAVIS_TAG" != "" ]]; then export DEPENDENCIES_BRANCH=$TRAVIS_TAG; fi
  - echo $DEPENDENCIES_BRANCH

install:
  - export BRANCH_REF=$DEPENDENCIES_BRANCH
  - haxelib install travix 0.0.12 --always
# hexCore
  - haxelib dev hexcore .
  - haxelib install haxelib.json --always
# hexLog
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexLog.git $BRANCH_REF --heads | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexLog.git ./hexlog
  - haxelib dev hexlog ./hexlog
# hexUnit
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexUnit.git $BRANCH_REF --heads | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexUnit.git ./hexunit
  - haxelib dev hexunit ./hexunit
#
  - haxelib path hexcore

script:
  - haxelib run travix:0.0.12 $HAXE_TARGET
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com
      - laurent@geturl.net
