language: haxe

haxe:
  - "3.2.1"
  - "3.3.0-rc.1"
  - development

matrix:
  allow_failures:
  - haxe: development
    
addons:
  apt:
    packages:
      # PHP
      - php5-cli
      # Flash
      - libcurl3:i386
      - libglib2.0-0:i386
      - libx11-6:i386
      - libxext6:i386
      - libxt6:i386
      - libxcursor1:i386
      - libnss3:i386
      - libgtk2.0-0:i386
  code_climate:
    repo_token: 965ee8e9015e381b2ed65de89ad1a09d092e978aaebf4e8e29e120b64d028d71
    
install:
  - git clone --recursive https://github.com/DoclerLabs/hexUnit.git ./hexunit
  - export DISPLAY=:99.0;
  - export AUDIODEV=null;
  - haxe flash/install.hxml

script:
  - if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-php.hxml && php bin/index.php; fi
  - haxe build-neko.hxml         && neko bin/MainCoreTest.n
  - haxe build-js.hxml           && node bin/MainCoreTest.js
  - if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/MainCoreTest.swf; fi
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com
      - laurent@geturl.net
